### ISSUE TITLE
Return the updated doc in the result

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/upsert#1]
Instead of just returning a result like

```js
{
  rev: '2-x',
  updated: true
}
```
We should return:

```js
{
  rev: '2-x',
  updated: true,
  doc: {/* ... */}
}
```
where `doc` is the newly updated document. We need this for https://github.com/pouchdb/mapreduce/pull/250

**Comment by sonofjack** [comment]
+1

**Comment by nolanlawson** [comment]
Nah
