### ISSUE TITLE
When will this be part of the main pouchDB repo?

### ISSUE THREAD

**Issue by raymatos** [pouchdb/upsert#11]

**Comment by nolanlawson** [comment]
It was already copied in: https://github.com/pouchdb/pouchdb/blob/8132c76b0a79b75a1ca7f19d1b85943869f6e47d/lib/deps/upsert.js. So this is now a totally separate module, and can live its own life independent of PouchDB.

**Comment by nolanlawson** [comment]
Or if you mean, will it ever *ship* with PouchDB as an exposed API, the answer is no.

**Comment by raymatos** [comment]
Right I was asking if you will bring it into pouchdb.  Seems like it would be a convenient API to have.  But I understand, if you want to keep pouchdb as close to couchdb as possible.

**Comment by nolanlawson** [comment]
Yes, and also it keeps the core size small.
