### ISSUE TITLE
Please support require.js AMD loading.

### ISSUE THREAD

**Issue by havocdrake** [pouchdb/upsert#12]
I loaded pouchdb-find just fine through AMD(require.js), but this plugin, i cant, i just returns undefined when i load it.

**Comment by nolanlawson** [comment]
We can do this by adding `--standalone pouchdbUpsert` to the `browserify` command. Anybody want to take this up?

**Comment by nolanlawson** [comment]
This is fixed in the latest release.

**Comment by atiertant** [comment]
@nolanlawson after loading it with requirejs =>

`ContactDBService.js:42 Uncaught TypeError: db.upsert is not a function`

```
paths: {
  'PouchDB': 'lib/pouchdb/pouchdb-5.3.2.min',
  'PouchDB-upsert': 'lib/pouchdb/pouchdb.upsert.min'
},
shim: {
  'PouchDB': {exports: 'PouchDB'},
  'PouchDB-upsert': { deps: ['PouchDB']}
}
```

where am i wrong?

**Comment by nolanlawson** [comment]
You probably also need to manually do `PouchDB.plugin(PouchUpsert)`
