### ISSUE TITLE
db.upsert diff function returns w/ `_rev` property

### ISSUE THREAD

**Issue by slang800** [pouchdb/upsert#2]
I find this rather odd because having a diff function eliminates the need for comparison based on revisions, and the `upsertInner` function handles setting the `_rev` for you. Could we get rid of ~~that~~ _the `_rev` property in the supplied document_, so I don't need to delete it, or is there a use-case for keeping it?

```coffeescript
db.upsert(post._id, (oldPost) ->
  delete oldPost._rev # would screw up the _.isEqual
  if _.isEqual(oldPost, post)
    console.log post._id, 'skipped'
    return false
  else
    console.log post._id, 'updated'
    return post
)
```

**Comment by nolanlawson** [comment]
I don't really understand your question? Do you want the `diffFun` to be passed a document that doesn't contain the `_rev`? Or what do you mean?

**Comment by slang800** [comment]
> Do you want the diffFun to be passed a document that doesn't contain the _rev?
yes, exactly.

**Comment by nolanlawson** [comment]
But what about the `_id`? Or the `_attachments`? Or `_deleted`? It's not really clear what to do about those. Also, it's not really clear what to do with first-generation documents (i.e. the doc doesn't exist yet) vs n+1th-generation documents (i.e the doc and rev both already exist).

**Comment by nolanlawson** [comment]
Closing for reasons described in https://github.com/pouchdb/upsert/pull/3
