### ISSUE TITLE
[feat] Typescript definition

### ISSUE THREAD

**Issue by keithdmoore** [pouchdb/upsert#24]
I realize Typescript definitions belong in the DefinitelyTyped library.  I am new to both Typescript and PouchDB.  I would like to use this upsert library and I wouldn't mind adding the Typings to DefinitelyTyped library for it but I am not really sure how to do it.

**Comment by nolanlawson** [comment]
I belive you just open a PR on DefinitelyTyped, yes? https://github.com/definitelytyped/definitelytyped

Looks like they have one directory per npm package, so you'd just create a directory called `pouchdb-upsert` and put the typings in there.

**Comment by keithdmoore** [comment]
I understand the process.  I am not sure how to define the Typings for the plugin.  I dont see any good examples for what I am trying to do there.

**Comment by nolanlawson** [comment]
Sorry, I'd help, but I don't know much about TypeScript...

**Comment by keithdmoore** [comment]
Thanks nolan, no worries. I am going to take a stab at it.  By the way, thanks for writing pouchdb!

**Comment by keithdmoore** [comment]
PR submitted in DefinitelyTyped https://github.com/DefinitelyTyped/DefinitelyTyped/issues/10596

**Comment by keithdmoore** [comment]
PR approved.  You can now access the typings via  `$ typings search pouchdb-upsert`
