### ISSUE TITLE
Make API consistent with 6.x pouchDB release

### ISSUE THREAD

**Issue by bhaskarvk** [pouchdb/upsert#28]
The 6.x release has removed `db.put(doc, id, rev)`
and replaced with `db.put({_id: id, _rev: rev, data: 'foo'})` instead. The upsert and putIfAbsent API calls should be changed similarly and their implementation should call the new APIs accordingly.

**Comment by nolanlawson** [comment]
I'm sorry, but I don't actually see where in the code we are calling the old API? Seems to me we're already using the new API: https://github.com/pouchdb/upsert/blob/7493014d01420a6acdeeeec82d251dbd63b2adbb/index.js#L39

**Comment by bhaskarvk** [comment]
Sorry my bad!
