### ISSUE TITLE
Master branch is broken in Travis

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/upsert#34]
See https://github.com/pouchdb/upsert/pull/32 and https://github.com/pouchdb/upsert/pull/31

Apparently some dependency broke because this was green the last time the build ran. I've enabled GreenKeeper and we'll see if we can hunt this down.

**Comment by nolanlawson** [comment]
fixed in #33

**Comment by nolanlawson** [comment]
Nope, master is _still_ broken. Apparently `npm run test-browser` passes on MacOS but fails on Travis Linux. Something different about Linux PhantomJS vs Mac PhanatomJS?

**Comment by AndreaGi** [comment]
@nolanlawson I don't think so, looks like more CouchDB is not running on Travis. Check the result on: https://travis-ci.org/pouchdb/upsert/jobs/207654791

**Comment by nolanlawson** [comment]
Thanks for the tip, I believe the issue turned out to be that CORS wasn't enabled on the CouchDB, which would explain why it failed in the browser but worked in Node. I wonder why it ever worked in the first place; maybe a bug in old PhantomJS?

In any case #44 appears to fix it, so I'll close this.
