### ISSUE TITLE
NPM install broken

### ISSUE THREAD

**Issue by useitsoftware** [pouchdb/upsert#39]
when i run npm install pouchdb-upsert, it runs into 

/my/npm/project/path/wich/is/an/angular2/ionic2/project
└── (empty)

npm ERR! code 1

is there any black magic to be done for it to work?  does it have something to do with the travis issue?

**Comment by useitsoftware** [comment]
npm install pouchdb-upsert@2.0.0 did work. something between 2.0.0 and 2.0.1 broke npm installer.

**Comment by nolanlawson** [comment]
I just published 2.1.0. Can you please check to see if everything is working? Also we would need a test case to reproduce if it's _not_ working. When you're using npm+Ionic+Angular+TypeScript+Webpack+whatever there are a million possible things that can go wrong. :)
